name: Code Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage
        run: npm run test:coverage
      - name: Check coverage
        run: |
          coverage=$(cat coverage/lcov.info | grep -Po '^SF:.*' | awk -F ':' '{s+=$2} END {print s}')
          if (( $(echo "$coverage < 80" | bc -l) )); then exit 1; fi