name: Code Coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run coverage

      - name: check
        uses: inzephirum/gha-test-coverage-check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_threshold: '80'
          report_file_path: './coverage/lcov.info'