name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
        env:
          CI: true
      - name: Check for linting errors
        if: failure()
        run: exit 1